# Generated by Django 6.0.2 on 2026-02-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('doctorName', models.CharField(max_length=100)),
                ('insuranceProvider', models.CharField(max_length=100)),
                ('policyNumber', models.CharField(max_length=100)),
            ],
        ),
    ]
