# Generated by Django 6.0.2 on 2026-02-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='fullName',
        ),
    ]
